app.js
demo/css/lumx.css
demo/includes/directives/text-fields/example.text-fields.html
js/text-field/js/lumx.text_field_directive.js
js/text-field/views/lumx.text_field.html
scss/main/objects/_objects.text-field.scss

We can now set a dark theme for text-fields and add an icon in front of text fields with fixed labels.

Feat text-fields: dark theme & text field with icon

---

modules/notification/js/notification_service.js

fix notification: applied correct position offset calculations

---

modules/date-picker/demo/includes/example.html
modules/date-picker/js/date-picker_directive.js
modules/date-picker/scss/_date-picker.scss
modules/date-picker/views/date-picker.html

Add allow-clear option able to reset input value

feat date picker: add allow clear option

---

modules/tooltip/scss/_tooltip.scss

Tooltip wasn't visible in dialogs

fix tooltip: increase z-index

---

modules/notification/js/notification_service.js

Otherwise, pressing the enter key may display the alert/confirm
multiple times

fix notification: blur the active element on displaying alert/confirm

---

modules/notification/js/notification_service.js

This allow to format the message (like using ```<br />``` tags) and use entities

feat notification: allow to display HTML

---

modules/select/js/select_directive.js

This improvement allow to have multiple node with directives, filters, ... as
a ```lx-select-selected``` template

feat select: allow to have complex selected template

---

README.md

I change default js path for each directive in index.html and dropdown template in dropdown directive.

change local port to 8080 for gulp

---

modules/select/js/select_directive.js

Properly inject in the correct controller

Fixed injecting into an incorrect controller

---

modules/dialog/demo/includes/basic.html

Regarding my last request, this is the correct version. Sorry.

Final typo fixed. Sorry, this is the correct version.

---

modules/select/js/select_directive.js

There was a bug in LxSelectChoicesController inject and I couldn't use the component in production environment.

Bug fixes for select choices

---

modules/notification/js/notification_service.js

When adding notifications quickly, one might get stuck on screen.

Fix notification stuck on screen

---

modules/select/js/select_directive.js

Backward compat for older transclusions

fix(select): handle backward compat for older transclusions

---

modules/checkbox/demo/checkbox.html
modules/checkbox/demo/includes/theme.html
modules/checkbox/js/checkbox_directive.js
modules/checkbox/scss/_checkbox.scss
modules/checkbox/views/checkbox.html

Hi,
I added theme support for checkbox.
Use light theme by default. No breaking change :)

feat(checkbox): add theme support

---

modules/stepper/js/stepper_directive.js
modules/stepper/views/step.html

Make cancel param optional , add a ng-if on cancel button.

feat(stepper): make cancel optional

---

modules/notification/demo/includes/basic.html
modules/notification/demo/js/demo-notification_controller.js
modules/notification/demo/notification.html
modules/notification/js/notification_service.js
modules/search-filter/demo/includes/autocomplete.html
modules/search-filter/demo/js/demo-search-filter_controller.js
modules/search-filter/demo/search-filter.html
modules/search-filter/js/search-filter_directive.js
modules/search-filter/views/search-filter.html

- adding a `delay` option for notifications
- add `on-select` option to autocomplete search-filter
- prevent search-filter clear button from submitting when used within a <form>

search filter & notification tweaks

---

modules/text-field/demo/includes/state.html
modules/text-field/demo/js/demo-text-field_controller.js
modules/text-field/demo/text-field.html
modules/text-field/js/text-field_directive.js

Add a new attribute to the textfield component to allow focusing an input straight away or whenever a flag is set as true

feat: textfield focus

---

modules/dropdown/demo/dropdown.html
modules/dropdown/js/dropdown_directive.js

Add a parameter to avoid going beyond screen edges
Also, fix the detection of mobile touch screen to remove hovering

fix(dropdown): ensure to not go beyond screen edges

---

modules/tabs/demo/includes/position.html
modules/tabs/demo/tabs.html
modules/tabs/js/tabs_directive.js
modules/tabs/scss/_tabs.scss
modules/tabs/views/tabs.html

Before it was not possible to setup tabs position. Now, by using "lx-position" attribute it is possible to move tabs to bottom or keep it in top position.

feat tabs: Add tabs position

---

modules/text-field/scss/_text-field.scss

Refine the css rule of the lx-text-field to be easily customizable.

feat(text-field): improve state color css

---

modules/dialog/demo/dialog.html
modules/radio-button/demo/radio-button.html
modules/stepper/demo/stepper.html
modules/switch/demo/switch.html

document a few changes that were done between 1.5.30 and 1.6.2

docs: 1.6.2 updates

---

modules/radio-button/js/radio-button_directive.js

Fix https://github.com/lumapps/lumX/issues/491
To test: Go to the components/radio-button page then test the default model value set and the first click.

Fix radio initial value & first click

---

modules/stepper/demo/includes/error.html
modules/stepper/demo/js/demo-stepper_controller.js
modules/stepper/js/stepper_directive.js

Add step validation when switching step with the navigation.

Fix stepper validation

---

modules/search-filter/demo/js/demo-search-filter_controller.js
modules/select/demo/includes/ajax.html
modules/select/demo/js/demo-select_controller.js

Fixes #541 
Update the AJAX examples so they hit an API that is working correctly (with no auth).
Now using the Star Wars API (https://swapi.co/)
To be tested:
- Select component (AJAX example)
- Search filter component

doc select: update ajax examples to use a working api

---

modules/select/demo/js/demo-select_controller.js
modules/select/scss/_select.scss
modules/select/views/select-choices.html

Each pane is independantly scrollable
Depends on #568

fix select: make the panes select scrollable

---

modules/select/js/select_directive.js
modules/select/views/select-choices.html
modules/select/views/select-selected-content.html

This allow to navigate in the panes and to toggle selections

feat select: support the arrow and enter keys in pane mode

---

modules/select/js/select_directive.js
modules/select/scss/_select.scss
modules/select/views/select-choices-accordion.html
modules/select/views/select-choices.html

In small screen (width under 980px) the multi panes select is displayed in accordion mode.

feat(select): add responsivity to select multi panes

---

modules/select/scss/_select.scss

Now text to long for the select width return to line

fix(default select): text-wrap

---

modules/dropdown/js/dropdown_directive.js
modules/dropdown/scss/_dropdown.scss

Fix a bug when selected an entry which is not visible, the choice is not toggle.

fix(dropdown): delete the height attribute in dropdown content class

---

.bowerrc
.gitignore
LICENSE.md
README.md
bower.json
build.sh
demo/includes/getting-started/customization/main.html
demo/includes/getting-started/installation.html
demo/includes/getting-started/installation/include.html
demo/index.html
gulpfile.js
package.json
release.py

Also improve package management (now use NPM/Yarn)

Add LumX in NPM

---

modules/dropdown/js/dropdown_directive.js
modules/dropdown/js/dropdown_service.js

Fix the `lx-close-on-click` issue

fix(dropdown): fix closeOnClick attribute usage

---

modules/select/js/select_directive.js

Adding `$timeout`s to handle unexpected digest cycles.

fix(dropdown-wait-for-digest): complete wait for digest on recompute

---

modules/dropdown/js/dropdown_service.js
modules/select/js/select_directive.js

Finally fixes scroll issue on choice selection in lx-select multiple

fix(dropdown-children-height): fix height change on choice

---

modules/select/js/select_directive.js

Dont apply bugfix logic if the dropdown isn't scrollable

fix(ls-select-multiple): dont apply logic when not scrolled

---

modules/select/js/select_directive.js

Correcting small typo that was causing minor bug

fix(typo): correcting small typo

---

gulpfile.js
package.json

Updates Material Design Icon font library.

feat(mdi): update mdi fonts

---

core/scss/tools/_tools.mdi.scss
modules/icon/demo/includes/simple-icons.html
package.json

Also add a backward for the `youtube` icon that was named `youtube-play`

feat(icons): update mdi

---

package.json

Fix angular and template cache versions.

chore: fix angular and template cache versions
