lumapps/lumX

js/select/js/lumx.select_directive.js

Hi,since you have changed 'model' to 'ngModel' to make a two-way data binding, there must use $scope.ngModel.$modelValue instead of $scope.model

change model to ngmodel

---

modules/fab/demo/includes/example.html
modules/fab/scss/_fab.scss

Before, one the FAB was clicked, then both icon appear on rollover. It
is now fixed.
Buttons that appear horizontally are now in a flex container : we don’t
need anymore <!— —> in the HTML to fix the inline-block space.

feat fab: click on fab and display flex

---

modules/dropdown/demo/includes/example.html
modules/dropdown/js/dropdown_directive.js

Before we needed to give a direction for the dropdown. Now it's
calculated regarding the height of the dropdown and the window.
Examples:
- Normal
- Not enough space at bottom but enough space at top
- Not enough space, more space at bottom
- Not enough space, more space at top

feat dropdown: direction automatic

---

modules/text-field/scss/_text-field.scss

Using Firefox when the text-field is invalid it has a border that it's from Firefox.
You can take a look here: http://ui.lumapps.com/directives/text-fields

fix text-field: remove border on firefox in invalid text fields

---

modules/date-picker/js/date-picker_directive.js

Before, a change in the model value doesn't affect the datepicker. The watch set on this update handle the case when we update the model binded to the datepicker.

fix date-picker: watch changes on model

---

modules/file-input/views/file-input.html
modules/select/views/select-selected.html
modules/text-field/views/text-field.html

Sanitized markup should be allowed within the labels of form fields. Strong, u, em, etc. Currently the label is displayed with curly braces, which will not allow html to be rendered. Instead, use ng-bind-html on the label and span elements to properly render html.
Fix #169

fix text-field, file-input: allow field labels to contain sanitized html

---

README.md
demo/includes/common/header.html
demo/includes/sidebar/sidebar-services.html
gulpfile.js
package.json

Hi!
In the header.html, the last link "Services" was reloading the whole app again, because of that target="_self".
I added a new possibility to run the app.
Just run 'gulp serve', without having to install Python SDK of Google App Engine.
Open this url: http://localhost:8080 and it's running

feature gulp-server: add gulp-server to init app

---

modules/dialog/js/dialog_directive.js

This will avoid to call the checkScrollEnd function leading to an
error because of the activeDialogId beeing undefined.
This fix can replace the previous one on this file (see PR #322)

fix dialog: unbind scroll event on close

---

core/js/lumx.js
core/js/utils/event-scheduler_service.js
demo/index.html
modules/dialog/js/dialog_directive.js
modules/dropdown/js/dropdown_directive.js
modules/notification/js/notification_service.js

This new feature will add the ability to close a dialog, dropdown or
confirm/alert with the escape key.
Moreover, for the confirm, the enter key will allow to validate the
confirm
Added with this feature is an event scheduler which allow to execute
events in the reverse order of events registration. This way, when
a dropdown opens in a dialog, the first escape key hit will close the
dropdown, the next one, the dialog.

feat: escape to close dialog/dropdown/confirm/alert

---

modules/tooltip/js/tooltip_directive.js

Without this fix, when two-way binding "lx-tooltip", the remains
displayed when changing the value of the tooltip.

feat tooltip: allow to update the tooltip content

---

modules/tooltip/js/tooltip_directive.js

This will fix any problems in ng-repeats
Fix #291

fix tooltip: don't destroy tooltip if undefined

---

modules/dialog/js/dialog_directive.js

It's now possible to pass a new parameter to dialog: 'before-close'.
This must point to a function that will be called just before closing the dialog.
If the function returns true, then the dialog is closed. If it returns false, the dialog is not
closed.
The function can also returns a promise. When the promise resolves, the dialog is closed.
If the promise is rejected (or never resolves), then the dialog is not closed.
This allow for example to ask confirmation to the user to close the dialog
(with LxNotificationService.confirm for example)

feat dialog: allow to cancel a dialog closing

---

CONTRIBUTING.md

Proably a type, should be gulp dist and not bower dist.

Fix build command in guide

---

gulpfile.js

Build output was incorrect on Windows. The problem is that Windows uses backslashes in file paths. Now the project is built on Windows too.
Fix #382

fix gulpfile: use cross-platform manipulations with file paths

---

modules/dialog/demo/includes/basic.html

I believe the doc should read `</lx-tab-panes>` rather than `</lx-panes>`

Fix typo in doc

---

modules/progress/scss/_progress.scss

Scaling X and Y in the horizontal bar problem does not make much sense and creates funny results if we decide to increase the height of the bar.

line progress should scale only the X axis

---

modules/date-picker/js/date-picker_directive.js

Add the clone() for the lastDayOfMonth in date-picker_directive.js LINE 135.
Cause the `var lastDayOfMonth = firstDayOfMonth.endOf('month');` will overwrite the `firstDayOfMonth` so the calendar will show the wrong day of week.

firstDayOfMonth issue.

---

modules/text-field/views/text-field.html

Prevents a lexerr in Angular to fix #444

Replace invisible 'Â' character with a space

---

modules/dialog/js/dialog_directive.js

`close` can be called by various event, particularly when the dialog is
destroyed. Thus, making the `lx-dialog__close-start` and `lx-dialog__
close-end` events beeing sent, even if the dialog wasn't really opened
The same case can occurs at opening.

fix dialog: only process closing if dialog is really opened

---

modules/tabs/js/tabs_directive.js

If links is not set at init, then the view mode is not set at 'separate'

fix(tabs): update the viewMode when links changes

---

bower.json
modules/select/demo/js/demo-select_controller.js
modules/select/js/select_directive.js

Not 100% sure what is going on with the transclude function... The clone element is different between 1.5.9 and latest angularjs (one is a text node, the other is a span element, which is why on the text node we don't have the outerHTML attr).
Maybe related to the jQuery update as well (jqLite / jQuery 3 ships in Angular 1.6.0)... @clementprevot may know?
Needs a bit of testing I reckon.

Fix/angular 1.6.0 upgrade fixes

---

bower.json

Freezing the bourbon version to the one just before they added all the deprecated warnings. This is temporary until we sort out those warnings to avoid messy console logs.

chore: freeze bourbon version until we sort out the warnings

---

modules/select/js/select_directive.js
package.json

Ensure that the choice being unselected really is in the model (to avoid
to splice with "-1" index, which will remove the last element of the
array).
Also, check with an `angular.equals` call to avoid to compare with
angular "things" in the objects

fix(select): fix the unselection of model

---

bower.json

Some icons like `format-align-justify` are missing with 1.8.36

fix: upgrade mdi to 1.9.33

---

core/scss/tools/_mixins.scss

Use new mdi function to avoid css error with bad name.
Before : If icon name doesn't existe, we have `content: "\";` 
The `/` escapes the `"` and next lines are commented.
Now :  If icon name doesn't existe, we have `content: ""` and a warning in Gulp .
Sample : 
`WARNING: Icon quote not found.
Backtrace: libs/mdi/scss/_functions.scss:16, in function 'mdi'
core/scss/tools/_mixins.scss:51, in mixin 'mdi-icon'
modules/radio-button/scss/_radio-button.scss:102`

fix(sass): update mdi-icon mixin

---

modules/search-filter/js/search-filter_directive.js

it was still triggering a search (even though it wasn't displaying anything) because we focus the input right away after clearing it

fix search-filter: clearing input should not trigger a search again

---

modules/notification/js/notification_service.js

Not only when there is an action.
This way, it allow to have an action when a notification closes, either
by clicking on it or when the delay is expired

feat(notification): always call the callback when the notif closes

---

modules/dropdown/js/dropdown_directive.js

when setting a specific px value on the lx-width attribute, we want to specifically set that width for the dropdown content rather than setting its min-width.
However, % values will continue to use min-width and will therefore adapt to the width of the content (if some content is larger).

fix dropdown: set dropdown width for px value and minWidth for %

---

modules/dialog/demo/dialog.html
modules/dialog/demo/js/demo-dialog_controller.js
modules/dialog/js/dialog_directive.js
modules/dialog/js/dialog_service.js

Allow to pass in extra parameters to the open and close method of a dialog so we can have extra logic when listening to the related events (open-start / open-end and close-start / close-end).
@clementprevot I have refactored your recent change with canceled so it's now an object rather than a boolean (so we can have multiple params and keep things clean).

feat dialog service extra parameters

---

modules/dialog/js/dialog_directive.js

Allowing user to close currently displayed dialog when no id is provided

feat(dialog-service-close): changing close trigger behavior

---

core/js/lumx.js
core/js/utils/misc.js
core/js/utils/utils_service.js
demo/index.html
modules/dropdown/js/dropdown_directive.js
modules/select/demo/includes/multipane.html
modules/select/demo/js/demo-select_controller.js
modules/select/demo/select.html
modules/select/js/select_directive.js
modules/select/scss/_select.scss
modules/select/views/select-choices.html
modules/select/views/select-selected-content.html
modules/select/views/select.html

This view mode allow to display multiple panes for selecting choices.
The choices must be provided according to a specific data model.
If filter is enable, then it will perform a search through the path of
the panes to search for matching items. Matching items will be
highlighted and containing panes will be auto-opened.
For more information regarding this view mode, see the examples

 feat select: add a "panes" choices view mode

---

modules/dropdown/js/dropdown_directive.js
modules/dropdown/scss/_dropdown.scss

If the content of the dropdown is to big to fit in the remaining of the
screen (to the top or the bottom according to the position of the target
of the dropdown), then make it scrollable.
Also, improve the recomputation of the height of the dropdown. Watch the
changes of the content instead of using an interval.

fix dropdown: make the dropdown scrollable

---

modules/select/demo/select.html
modules/select/scss/_select.scss

Fix the text suprposition problem when pane content is too long to be displayed in one line.

fix(select-multi-panes): fix text superposition in responsive mode

---

core/js/utils/misc.js
modules/select/js/select_directive.js
modules/select/views/select-choices.html
modules/select/views/select-selected-content.html

This way, there is no chances of conflict with other libs
BROKEN:
The `stopPropagation` directive has been renamed to `lxStopPropagation`
The `highlight` filter has been renamed to `lxHighlight`

fix: remove unused misc directives and rename other

---

core/js/utils/utils_service.js

This PR fixes the scroll bug when we are using nested `lx-dropdown` 
0. Be sure your page is wide enough, you should be able to scroll on Y axis
1. Set nested dropdown in a page
2. Open all the dropdowns
3. When clicking away, the dropdowns are closing
4. You should be able to scroll again and the window in not auto scrolling to the top

fix(dropdown-scroll): removing body scroll bug for nested dropdown

---

modules/tabs/scss/_tabs.scss
modules/tabs/views/tabs-panes.html

this display issue was introduced by 20bfe180b988c84b0aef73785b3e752ed0d620cf
Fixes #583 
- Go to the tabs component page (`/components/tabs`) and check that all first tabs are displayed as expected
- Go to any documentation page and toggle the code samples (via the < > icon)
--> check that the tabs panes are displayed ok

fix tabs: only display none by default for separate layout

---

modules/dropdown/js/dropdown_service.js
modules/select/js/select_directive.js

Fixes the dropdown directive scrollTop reset bug when a choice is toggled from a scrollable multiple select.
When a choice was toggled, the `ng-repeat` which was rendered in the dropdown directive was recompiled each time a change was made il the attached `ng-model`. This was causing the `scrollTop` reset on the dropdown element.

fix(lx-choices): dropdown directive wont scroll top on choice change

---

modules/select/js/select_directive.js

https://ui.lumapps.com/components/select
Type `age` in multipane select and see result `Male humans > middle aged` without space beetween `middle` and `aged`

fix(lx-select): fix highlight in 'pane' view mode

---

modules/progress/js/progress_directive.js
modules/progress/views/progress.html

**Browsers**
Chromium v67.0.3387.0
Safari v11.0.2
The ScreenShot above shows `div.progress-container--indeterminate` class not activated. So I switched to using `?:`operator, which activates `? 'determinate' : 'indeterminate'` depending on the `lx-value` value, set as an attribute by the user.
The ScreenShot above shows `div.progress-container--indeterminate` activated and running fine.
**Note**: Bug and Fixes on both browsers listed above.

fix(progress): change from ng-class to class ternary

---

modules/dropdown/js/dropdown_directive.js

With iOS, the dropdown can't be closed.
This fix use 'ontouchstart' event when touch event is available instead of the `click` event.
**Test**
- try to open/close a dropdown with iOS

fix(dropdown): fix closing with iOS

---

modules/dropdown/js/dropdown_directive.js

Fix the dropdown in responsive mode 
1. Open Dropdown component page
2. Change view mode for responsive mode (Nexus 5x for example)
3. Try to open a dropdown, scroll in dropdown menu
4. Click on a link in the dropdown menu, be sure the click/touch event is not intercept by the element dehind the menu link you've just clicked.

fix(dropdown): fix dropdown with touch events

---

modules/fab/js/fab_directive.js

Fix the behavior on the trigger-on-click if attribute is set to false.
1. Edit basic.html of FAB Button demo to add the attribute `trigger-on-click="false"`
2. Refresh the FAB page
3. hover the FAB button you've just edit, the fab actions shoud appear

fix(fab): fix behavior of triggerOnClick attribute is set to false

---

modules/tooltip/js/tooltip_directive.js

Disable the tooltip events on mobile screens (<768px)

fix(tooltip: disable tooltip on mobile screens

---

core/js/utils/utils_service.js
modules/dropdown/js/dropdown_directive.js

With iOS, dropdown position can be have a wrong position because when a dropdown is open the body becomes fixed.
I remove this fixed and I close the dropdown when we scroll or click outside the dropdown.

fix(dropdown): update logic for ios

---

modules/progress/js/progress_directive.js
modules/progress/scss/_progress.scss
modules/progress/views/progress.html

Chrome (Version 67.0.3396.87 (Official Build) (64-bit)) has rendering artifacts when SVG elements are animated in an also animated HTML container when the viewport zoom is other than 100%. This makes the circular `lx-progress` component wobble.
The fix consists of moving the animation behavior from the `svg` element (which is an HTML node) to a `g` (which is an SVG node). With all the animation happening in the `svg` land, the Chrome rendering pipeline works better.
1. Go to the [`lx-progress` demo](https://ui.lumapps.com/components/progress).
2. Click on the `toggle circular progress` button.
3. Zoom-out and resize the window until you see that the `lx-progress` wobbles.

fix(progress): prevent animation wobble

---

modules/dropdown/js/dropdown_directive.js

When we open a dropdown, the mask is useful only if we open the dropdown by a click.
If the directive has a `lx-hover = true` the dropdown will been closed when the dropdown loses its hover state.

fix(dropdown): add mask only if hover is false

---

demo/includes/css/color/palette.html

Changed the number of items per row and boom, it's fixed ;)
It's even on par with the Material Design docs on https://material.io/design/color/the-color-system.html#tools-for-picking-colors :D

docs: fix css color names display

---

launch.sh

Since the latest AppEngine update, relative path doesn't work anymore.

fix(dev-server): fix the path to launch the dev server

---

modules/text-field/demo/includes/basic.html
modules/text-field/demo/js/demo-text-field_controller.js
modules/text-field/js/text-field_directive.js
modules/text-field/views/text-field.html

This param allow to have a placeholder on the transcluded input type.
This way, the label always stays on top of the field.
This param is not compatible with the `fixedLabel` param

feat(text-field): add a new `hasPlaceholder` param

---

core/scss/generic/_generic.normalize.scss

Fix the issue in ie11 described in lum-1900 that was causing a big cross left to the normal lumx clear-cross to appear.

fix: clear cross in text field in ie11

---

modules/select/scss/_select.scss
modules/select/views/select-choices.html

Removes the infinite scroll loader from the top of the dropdown so that we can see it correctly when scrolling.

feat(infinite-scroll-loader): move to correct position

---

modules/dropdown/js/dropdown_directive.js
modules/dropdown/scss/_dropdown.scss

The dropdown menu was only hidden with an opacity: 0, so it remained selectable even when the dropdown menu was closed.
Added visibility hidden/visible to prevent any events on the dropdown without modifying current behavior (styles, animations, ...)

fix(dropdown): fix dropdown visibility when closed
